"""Build RVPort with Xcode clang or a local Zig compiler plus an iOS SDK."""
import argparse
import base64
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parent

def materialize_sdk_file_links(sdk):
    """Git on Windows represents SDK symlinks as tiny text files."""
    if os.name != 'nt' or not (sdk.parent/'.git').exists(): return
    data=subprocess.check_output(['git','-C',str(sdk.parent),'ls-files','-s','-z',sdk.name])
    pending=[]
    for record in data.split(b'\0'):
        if not record:continue
        meta,name=record.split(b'\t',1)
        if not meta.startswith(b'120000 '):continue
        path=sdk.parent/name.decode()
        if path.is_file() and path.stat().st_size < 2048:
            target=(path.parent/path.read_text().strip()).resolve()
            if target.is_file():pending.append((path,target))
    for _ in range(8):
        progress=False
        for path,target in list(pending):
            if any(target==p for p,t in pending):continue
            path.write_bytes(target.read_bytes());pending.remove((path,target));progress=True
        if not progress:break

def build(sdk=None, zig=None):
    out=ROOT/'build';out.mkdir(exist_ok=True)
    logo=(ROOT/'native/assets/ReVancedSettings.png').read_bytes()
    encoded=base64.b64encode(logo).decode('ascii')
    (out/'RVSettingsIconData.h').write_text('// Generated by build.py from the supplied logo.\nstatic NSString *const RVSettingsIconBase64=\n'+
        '\n'.join('@"'+encoded[i:i+120]+'"' for i in range(0,len(encoded),120))+';\n',encoding='ascii')
    from features import native_header
    (ROOT/'native/RVFeatures.h').write_bytes(native_header().encode('utf-8'))
    from settings_catalog import native_header as settings_header
    (ROOT/'native/RVSettingsCatalog.h').write_bytes(settings_header().encode('utf-8'))
    source_files={p.relative_to(ROOT/'native').as_posix():hashlib.sha256(p.read_bytes()).hexdigest()
                  for p in sorted((ROOT/'native').rglob('*')) if p.is_file()}
    source_fingerprint=hashlib.sha256(''.join(f'{name}:{digest}\n' for name,digest in source_files.items()).encode()).hexdigest()
    (out/'RVBuildIdentity.h').write_text('// Generated source identity for device diagnostic reports.\n'
        '#define RV_BUILD_SOURCE_SHA256 @"'+source_fingerprint+'"\n',encoding='ascii')
    if sys.platform == 'darwin' and not zig:
        sdk=Path(sdk or subprocess.check_output(['xcrun','--sdk','iphoneos','--show-sdk-path'],text=True).strip())
        compiler=['xcrun','--sdk','iphoneos','clang','-target','arm64-apple-ios17.0']
    else:
        sdk=Path(sdk or ROOT/'.tools/sdks/iPhoneOS16.5.sdk').resolve()
        zig=Path(zig or ROOT/'.tools/python/ziglang/zig.exe').resolve()
        if not zig.exists() or not sdk.is_dir():
            raise RuntimeError('Need --zig <zig executable> and --sdk <iPhoneOS SDK>, or build on macOS with Xcode')
        materialize_sdk_file_links(sdk)
        compiler=[str(zig),'cc','-target','aarch64-ios.17.0']
    args=compiler+['-isysroot',str(sdk),'-isystem',str(sdk/'usr/include'),'-L'+str(sdk/'usr/lib'),
        '-F'+str(sdk/'System/Library/Frameworks'),'-F'+str(sdk/'System/Library/PrivateFrameworks'),
        '-fobjc-arc','-fblocks','-O2','-g','-save-temps=obj','-Wall','-Wextra',
        '-Werror','-Wno-unused-parameter','-fvisibility=hidden','-dynamiclib',
        str(ROOT/'native/RVPort.m'),'-o',str(out/'RVPort.dylib'),
        '-framework','Foundation','-framework','UIKit','-framework','ImageIO','-framework','NaturalLanguage','-framework','CoreImage','-framework','AVFoundation','-framework','MediaPlayer','-framework','CoreGraphics','-framework','QuartzCore','-framework','Network','-framework','Security','-lobjc',
        '-Wl,-install_name,@executable_path/Frameworks/RVPort.dylib',
        '-Wl,-headerpad,0x4000']
    with (out/'build.log').open('w',encoding='utf-8') as log:
        result=subprocess.run(args,stdout=log,stderr=subprocess.STDOUT)
    if result.returncode:
        print((out/'build.log').read_text(),file=sys.stderr)
        raise RuntimeError(f'Compiler exited {result.returncode}')
    if sys.platform == 'darwin' and not zig:
        symbol_folder = out/'RVPort.dSYM'
        subprocess.run(['xcrun', 'dsymutil', str(out/'RVPort.dylib'), '-o', str(symbol_folder)], check=True)
        shutil.make_archive(str(out/'RVPort.dSYM'), 'zip', out, 'RVPort.dSYM')
    from patcher import payload
    binary=payload(out/'RVPort.dylib')
    from macho import MachO
    image=MachO(binary)
    padding=binary[image.end:image.first_content]
    if len(padding)<16 or any(padding):
        raise RuntimeError('Built dylib has no zero-filled header space for the signing load command')
    source=(ROOT/'native/RVPort.m').read_bytes()
    final_sources={p.relative_to(ROOT/'native').as_posix():hashlib.sha256(p.read_bytes()).hexdigest()
                   for p in sorted((ROOT/'native').rglob('*')) if p.is_file()}
    if final_sources != source_files:
        raise RuntimeError('Native sources changed during compilation; rebuild before packaging')
    metadata={'payload_sha256':hashlib.sha256(binary).hexdigest(),'source_sha256':hashlib.sha256(source).hexdigest(),
              'build_source_sha256':source_fingerprint,
              'source_files':source_files,
              'compiler_command':args,'sdk':str(sdk),'signing_header_padding_bytes':len(padding),'runtime_validated':False,
              'debug_symbols': 'RVPort.dSYM.zip' if sys.platform == 'darwin' and not zig else None}
    (out/'build-manifest.json').write_text(json.dumps(metadata,indent=2),encoding='utf-8')
    print(f'Built {out / "RVPort.dylib"} ({len(binary):,} bytes)')

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--sdk');p.add_argument('--zig');a=p.parse_args()
    try:build(a.sdk,a.zig)
    except (RuntimeError,OSError,ValueError) as ex:print(f'Build error: {ex}',file=sys.stderr);raise SystemExit(2)
