"""Embed the supplied settings logos without running a native build.

PNG bytes remain unchanged. The simple DeArrow SVG becomes UIKit cubic paths,
preserving its viewBox and CSS fill overrides without a runtime SVG dependency.
Run with --check to verify the checked-in header still matches the source assets.
"""
import argparse
import base64
import hashlib
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
ASSETS = ROOT / 'native/assets/settings'
OUTPUT = ROOT / 'native/RVSettingsBrandIconData.h'
NUMBER = r'[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?'
TOKEN = re.compile(r'[MmCcSsZz]|' + NUMBER)


def svg_paths():
    svg = ET.fromstring((ASSETS / 'DearrowLogo.svg').read_bytes())
    box = [float(n) for n in svg.attrib['viewBox'].split()]
    assert box == [0, 0, 36, 36], 'Unexpected DeArrow SVG coordinates'
    paths = []
    for element in svg.findall('{http://www.w3.org/2000/svg}path'):
        styles = dict(part.strip().split(':', 1) for part in element.attrib.get('style', '').split(';') if ':' in part)
        assert float(styles.get('fill-opacity', '1')) == 1
        fill = styles.get('fill', element.attrib['fill'])
        assert re.fullmatch(r'#[0-9a-fA-F]{6}', fill)
        data = element.attrib['d']
        assert not TOKEN.sub('', data).strip(' ,\t\r\n'), 'Unsupported SVG path command'
        tokens = TOKEN.findall(data)
        position = (0.0, 0.0)
        start = position
        control = None
        commands = []
        index = 0
        command = None
        while index < len(tokens):
            if tokens[index].isalpha():
                command = tokens[index]
                index += 1
            assert command is not None
            kind = command.upper()
            relative = command.islower()
            if kind == 'Z':
                commands.append(('Z', ()))
                position, control, command = start, None, None
                continue
            count = {'M': 2, 'C': 6, 'S': 4}[kind]
            values = [float(n) for n in tokens[index:index + count]]
            assert len(values) == count
            index += count
            points = [(values[i] + (position[0] if relative else 0), values[i + 1] + (position[1] if relative else 0)) for i in range(0, count, 2)]
            if kind == 'M':
                start = position = points[0]
                control = None
                commands.append(('M', position))
                command = None  # The supplied SVG has no implicit lineto segments.
            else:
                if kind == 'S':
                    first = (2 * position[0] - control[0], 2 * position[1] - control[1]) if control is not None else position
                    points.insert(0, first)
                commands.append(('C', tuple(n for point in points for n in point)))
                control, position = points[1], points[2]
        paths.append((fill, commands))
    assert len(paths) == 3
    return paths


def generated_header():
    lines = ['// Generated by settings_brand_icons.py from the supplied logos.',
             '// PNG bytes are embedded exactly; SVG paths preserve their original colors.']
    for filename, symbol in [('ReturnYTDislike.png', 'RVSettingsRYDBrandBase64'), ('LogoSponsorBlock256px.png', 'RVSettingsSponsorBrandBase64')]:
        data = (ASSETS / filename).read_bytes()
        encoded = base64.b64encode(data).decode('ascii')
        lines += [f'// {filename} SHA256: {hashlib.sha256(data).hexdigest()}', f'static NSString *const {symbol}=']
        lines += ['@"' + encoded[i:i + 120] + '"' for i in range(0, len(encoded), 120)]
        lines[-1] += ';'
    svg = (ASSETS / 'DearrowLogo.svg').read_bytes()
    lines += [f'// DearrowLogo.svg SHA256: {hashlib.sha256(svg).hexdigest()}',
              'static UIImage *RVSettingsDeArrowBrandImage(void) {',
              '    static UIImage *image;static dispatch_once_t once;',
              '    dispatch_once(&once,^{',
              '        UIGraphicsImageRenderer *renderer=[[UIGraphicsImageRenderer alloc] initWithSize:CGSizeMake(24,24)];',
              '        image=[[renderer imageWithActions:^(UIGraphicsImageRendererContext *context) {',
              '            CGContextScaleCTM(context.CGContext,24.0/36,24.0/36);']
    for index, (fill, commands) in enumerate(svg_paths()):
        path = f'path{index}'
        lines.append(f'            UIBezierPath *{path}=[UIBezierPath bezierPath];')
        for kind, values in commands:
            n = [format(value, '.17g') for value in values]
            if kind == 'M':
                lines.append(f'            [{path} moveToPoint:CGPointMake({n[0]},{n[1]})];')
            elif kind == 'C':
                lines.append(f'            [{path} addCurveToPoint:CGPointMake({n[4]},{n[5]}) controlPoint1:CGPointMake({n[0]},{n[1]}) controlPoint2:CGPointMake({n[2]},{n[3]})];')
            else:
                lines.append(f'            [{path} closePath];')
        r, g, b = (int(fill[i:i + 2], 16) for i in (1, 3, 5))
        lines += [f'            [[UIColor colorWithRed:{r}.0/255 green:{g}.0/255 blue:{b}.0/255 alpha:1] setFill];', f'            [{path} fill];']
    lines += ['        }] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];', '    });return image;', '}']
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    header = generated_header()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != header:
            parser.exit(1, 'Embedded settings logos differ from their source assets; run settings_brand_icons.py\n')
        print('Embedded PNG bytes and all three SVG paths match the supplied assets')
    else:
        OUTPUT.write_bytes(header.encode('utf-8'))
        print(f'Updated {OUTPUT.name}; no native build performed')


if __name__ == '__main__':
    main()
